apiVersion: xmova/v1
kind: Pipeline
metadata:
  name: 318123251--318123251_src_app_screens--ResumoCheckListDetail
  labels:
  - recordDetail fields=data,descricao,tipoResposta,observacao labels
pipeline:
  tasks:
  - id: get__checklistRespondido
    name: get__checklistRespondido
    run:
      type: resource_query
      resource: _checklistRespondido
  - id: query__checklistRespondido
    name: query__checklistRespondido
    run:
      type: sql
      sql: select * from ResumoCheckList
  - id: recorddetail_fields_3
    name: recorddetail_fields
    run:
      type: emit
    outputs:
    - name: data
    - name: descricao
    - name: tipoResposta
    - name: observacao
hooks:
  beforeInit:
  - _checklistRespondido: select * from ResumoCheckList
  - _checklistRespondido: 'null'
resources:
- name: _checklistRespondido
  type: sql
  sql: select * from ResumoCheckList
secrets: {}
