apiVersion: xmova/v1
kind: Pipeline
metadata:
  name: 318123230--318123230_src_app_screens--ResumoApontamentoDetail
  labels:
  - recordDetail fields=data,tipoOperacao,placa,motorista,telefone,material,unidade,quantidade,desconto,quantidadeFinal,origem,destino,kmEstaca,mEstaca,distancia,apontador
    labels
pipeline:
  tasks:
  - id: get__lastApontamento
    name: get__lastApontamento
    run:
      type: resource_query
      resource: _lastApontamento
  - id: query__lastApontamento
    name: query__lastApontamento
    run:
      type: sql
      sql: select * from ResumoApontamento
  - id: recorddetail_fields_3
    name: recorddetail_fields
    run:
      type: emit
    outputs:
    - name: data
    - name: tipoOperacao
    - name: placa
    - name: motorista
    - name: telefone
    - name: material
    - name: unidade
    - name: quantidade
    - name: desconto
    - name: quantidadeFinal
    - name: origem
    - name: destino
    - name: kmEstaca
    - name: mEstaca
    - name: distancia
    - name: apontador
hooks:
  beforeInit:
  - _lastApontamento: select * from ResumoApontamento
  - _lastApontamento: 'null'
resources:
- name: _lastApontamento
  type: sql
  sql: select * from ResumoApontamento
secrets: {}
