apiVersion: xmova/v1
kind: Pipeline
metadata:
  name: 363123252--363123252_src_app_screens--ResumoApontamentoDetail
  labels:
  - recordDetail fields=tipoOper,dataInicial,dataFinal,duracao,medicaoAtual,oper,perda,postoAbastecimento,combustivel,quantidadeAbastecida,caminhao
    labels
pipeline:
  tasks:
  - id: get__lastApontamento
    name: get__lastApontamento
    run:
      type: resource_query
      resource: _lastApontamento
  - id: query__lastApontamento
    name: query__lastApontamento
    run:
      type: sql
      sql: select * from ResumoApontamento
  - id: recorddetail_fields_3
    name: recorddetail_fields
    run:
      type: emit
    outputs:
    - name: tipoOper
    - name: dataInicial
    - name: dataFinal
    - name: duracao
    - name: medicaoAtual
    - name: oper
    - name: perda
    - name: postoAbastecimento
    - name: combustivel
    - name: quantidadeAbastecida
    - name: caminhao
hooks:
  beforeInit:
  - _lastApontamento: select * from ResumoApontamento
  - _lastApontamento: 'null'
resources:
- name: _lastApontamento
  type: sql
  sql: select * from ResumoApontamento
secrets: {}
